name: 'Create Release from PR'
description: 'Create a GitHub release from a PR'
branding:
  icon: 'package'
  color: 'green'
inputs:
  token:
    description: "Github token (with release permissions)"
    required: true
  repo:
    description: "Source repository"
    required: false
    default: ${{ github.repository }}
  branch:
    description: "Source branch"
    required: false
    default: main
  title:
    description: "Pull Request title"
    required: false
    default: ${{ github.event.pull_request.title }}
  prerelease:
    description: "Whether or not this is a prelease"
    required: false
    default: false
  latest:
    description: "Whether or not this should be the latest release"
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.title }}
    - ${{ inputs.prerelease }}
    - ${{ inputs.latest }}
